repository: GpuZelenograd/GpuZelenograd.github.io
title: GpuZelenograd
theme: jekyll-theme-leap-day
plugins:
  - jekyll-redirect-from
  - jekyll-optional-front-matter
markdown: kramdown
permalink: /:slug
optional_front_matter:
  remove_originals: true
include:
  - README.md
defaults:
  -
    scope:
      path: "README."
    values:
      lang: en-US
      pagelang2: en
      title: GpuZelenograd
      description: list of our utilities and resources
      seo:
        type: LocalBusiness
      redir_js: if (/^RU/i.test(navigator.language) && !/noredirect/.test(window.location.search)) window.location.replace("/" + window.location.search)
      redirect_from:
      - /readme
      - /Readme
      - /READme
      - /readMe
      - /ReadMe
      - /READMe
      - /readME
      - /ReadME
